development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: book_nest_development

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: book_nest_production
